apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: store
    name: in-cluster
  project: appbundle-project
  source:
    path: ./release
    repoURL: https://github.com/cbrech/microservices-demo.git
    targetRevision: main
  syncPolicy:
                automated:
                  prune: true
                  selfHeal: true


---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: store
    app.kubernetes.io/component: namespace
  name: store
  
---
  
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: store
 namespace: store
spec:
  gateways:
    - istio-system/public
  hosts:
   - store.militarycoders.us
  http:
  - route:
    - destination:
        port:
          number: 80
        host: frontend
