apiVersion: apps/v1
kind: Deployment
metadata:
  name: demeter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demeter
  template:
    metadata:
      labels:
        app: demeter
    spec:
      imagePullSecrets:
      - name: registry-il2
      containers:
      - image: registry.bigbang.dev:5000/demeter:0.0.1
        name: demeter
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demeter
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demeter
---