apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2d2-app
spec:
  revisionHistoryLimit: 1
  selector:
       matchLabels:
        app: c2d2-app
  template:
    metadata:
      labels:
        app: c2d2-app
  template:
    spec:
      terminationGracePeriodSeconds: 15
      containers:
      - name: c2d2
        image: registry.bigbang.dev:5000/c2d2:1.0.5
        imagePullPolicy: Always
        env:
        - name: DatabaseSettings__DatabaseName
          value: "C2D2"
        - name: "DatabaseSettings__ConnectionString"
          value: "mongodb://mongodb:27017"
        - name: "USE_DEV_JWT"
          value: "true"
        - name: "C2D2_DEV_USER"
          value: "Admin"
        - name: "Logging__LogLevel__C2D2"
          value: "Warning"
        - name: "UdlSettings__Endpoint"
          value: "https://unifieddatalibrary.com/"
        - name: "UdlSettings__Send"
          value: "false"
        - name: "UdlSettings__Receive"
          value: "false"
        - name: "UdlSettings__InstanceId"
          value: "NUCLEUS_1"
        - name: "LocalSettings__DefaultTags"
          value: "Nucleus1"
---
apiVersion: v1
kind: Service
metadata:
  name: c2d2-app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2d2-mongodb
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: c2d2-mongodb
  template:
    metadata:
      labels:
        app: c2d2-mongodb
    spec:
      imagePullSecrets:
      - name: private-registry
      containers:
      - name: mongodb
        image: docker.io/mongo:5.0.10
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "5"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        ports:
        - name: mongo
          containerPort: 27017
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 25
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        command: ["/usr/bin/mongod"]
        args: ["--tlsMode", "disabled", "--bind_ip_all"]
        resources:
          limits:
            memory: 2Gi


---
apiVersion: v1
kind: Service
metadata:
  name: c2d2-mongodb
spec:
  selector:
    app: c2d2-mongodb
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017

