

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: podinfo
    name: in-cluster
  project: appbundle-project
  source:
    path: ./chart
    repoURL: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/podinfo.git
    targetRevision: 6.0.0-bb.4
  values:
    ui:
    color: "#dddddd"
    message: "Hi"
    logo: ""
  syncPolicy:
                automated:
                  prune: true
                  selfHeal: true


---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/component: namespace
  name: podinfo

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: podinfo
 namespace: podinfo
spec:
  gateways:
    - istio-system/public
  hosts:
   - podinfo.bigbang.dev
  http:
  - route:
    - destination:
        port:
          number: 9898
        host: podinfo-app
