apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: takserver
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: takserver
    name: in-cluster
  project: appbundle-project
  source:
    path: ./src/takserver-cluster/deployments
    repoURL: https://github.com/cbrech/takserver.git
    targetRevision: main
  syncPolicy:
                automated:
                  prune: true
                  selfHeal: true



  
---
  
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: takserver
 namespace: takserver
spec:
  gateways:
    - istio-system/public
  hosts:
   - tak.militarycoders.us
  http:
  - route:
    - destination:
        port:
          number: 80
        host: frontend
