apiVersion: apps/v1
kind: Deployment
metadata:
  name: demeter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demeter
  template:
    metadata:
      labels:
        app: demeter
    spec:
      imagePullSecrets:
      - name: registry-il2
      containers:
      - image: registry.bigbang.dev:5000/demeter:0.0.1
        name: demeter
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demeter
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demeter
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demeter-mongodb
  namespace: demeter
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demeter
    name: in-cluster
  project: appbundle-project
  source:
    path: ./bitnami/mongodb
    repoURL: https://github.com/cbrech/bitnamicharts.git
    targetRevision: b
    helm:
      parameters:
      - name: auth.enabled
        value: "false"
  syncPolicy:
                automated:
                  prune: true
                  selfHeal: true
---


apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: demeter
    app.kubernetes.io/component: namespace
  name: demeter

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: demeter
 namespace: demeter
spec:
  gateways:
    - istio-system/public
  hosts:
   - demeter.bigbang.dev
  http:
  - route:
    - destination:
        port:
          number: 80
        host: demeter
