apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c2d2-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: c2d2
    name: in-cluster
  project: appbundle-project
  source:
    path: ./apps/c2d2-chart
    repoURL: https://github.com/cbrech/argo-cd-AoA-parent.git
    targetRevision: HEAD
  syncPolicy:
                automated:
                  prune: true
                  selfHeal: true

---


apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: c2d2
    app.kubernetes.io/component: namespace
  name: c2d2

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: c2d2
 namespace: c2d2
spec:
  gateways:
    - istio-system/public
  hosts:
   - c2d2.bigbang.dev
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: c2d2-app
