apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: takserver
    name: in-cluster
  project: appbundle-project
  source:
    path: ./apps/takserver
    repoURL: https://github.com/cbrech/argo-cd-AoA-parent.git
    targetRevision: HEAD
  syncPolicy:
                automated:
                  prune: true
                  selfHeal: true