apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: guestbook-dev
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: ./guestbook
    repoURL: https://github.com/cbrech/argocd-example-apps.git
    targetRevision: HEAD

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: guestbook-dev
    app.kubernetes.io/component: namespace
  name: guestbook-dev
  
---
  
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: guestbook
 namespace: guestbook-dev

spec:
  gateways:
    - "istio-system/public"
  hosts:
   - guestbook.bigbang.dev
  http:
  - route:
    - destination:
        port:
          number: 80
        host: guestbook-ui.guestbook-dev.svc.cluster.local
