apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook-dev
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: ./apps
    repoURL: https://github.com/cbrech/argocd-example-apps.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Namespace
metadata:
  name: guestbook
