apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yelb-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: yelb-dev
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: ./deployments/platformdeployment/Kubernetes/chart/yelb/
    repoURL: https://github.com/mreferre/yelb.git
    targetRevision: HEAD
  syncPolicy:
                automated:
                  prune: true
                  selfHeal: true

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: yelb-dev
    app.kubernetes.io/component: namespace
  name: yelb-dev
  
---
  
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: yelb
 namespace: yelb-dev
spec:
  gateways:
    - istio-system/public
  hosts:
   - guestbook.militarycoders.us
  http:
  - route:
    - destination:
        port:
          number: 80
        host: yelb
